package com.newput.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.newput.domain.Employee;
import com.newput.domain.EmployeeExample;

public interface EmployeeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	int countByExample(EmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	int deleteByExample(EmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	int insert(Employee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	int insertSelective(Employee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	List<Employee> selectByExample(EmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	Employee selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	int updateByExampleSelective(@Param("record") Employee record, @Param("example") EmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	int updateByExample(@Param("record") Employee record, @Param("example") EmployeeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	int updateByPrimaryKeySelective(Employee record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	int updateByPrimaryKey(Employee record);
	
<<<<<<< HEAD
	
	/**
	 * user defined mapper. This method corresponds to the database table employee
	 * @param record
	 * @return
	 */
	Employee selectByEmailPassword(Employee record);

	int selectByEmailId(Employee record);
	
	void updateByEmail(Employee record);

=======
	int selectByEmailId(Employee record);
	
	void updateByEmail(Employee record);
>>>>>>> e44a126... Verify mail and update flag
}