package com.newput.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.newput.domain.Session;
import com.newput.domain.SessionExample;

public interface SessionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table session
	 * @mbggenerated  Wed Oct 07 14:48:54 IST 2015
	 */
	int countByExample(SessionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table session
	 * @mbggenerated  Wed Oct 07 14:48:54 IST 2015
	 */
	int deleteByExample(SessionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table session
	 * @mbggenerated  Wed Oct 07 14:48:54 IST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table session
	 * @mbggenerated  Wed Oct 07 14:48:54 IST 2015
	 */
	int insert(Session record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table session
	 * @mbggenerated  Wed Oct 07 14:48:54 IST 2015
	 */
	int insertSelective(Session record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table session
	 * @mbggenerated  Wed Oct 07 14:48:54 IST 2015
	 */
	List<Session> selectByExample(SessionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table session
	 * @mbggenerated  Wed Oct 07 14:48:54 IST 2015
	 */
	Session selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table session
	 * @mbggenerated  Wed Oct 07 14:48:54 IST 2015
	 */
	int updateByExampleSelective(@Param("record") Session record, @Param("example") SessionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table session
	 * @mbggenerated  Wed Oct 07 14:48:54 IST 2015
	 */
	int updateByExample(@Param("record") Session record, @Param("example") SessionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table session
	 * @mbggenerated  Wed Oct 07 14:48:54 IST 2015
	 */
	int updateByPrimaryKeySelective(Session record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table session
	 * @mbggenerated  Wed Oct 07 14:48:54 IST 2015
	 */
	int updateByPrimaryKey(Session record);
}