package com.newput.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.newput.domain.TimeSheet;
import com.newput.domain.TimeSheetExample;

public interface TimeSheetMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table time_sheet
	 * 
	 * @mbggenerated Mon Oct 12 13:12:27 IST 2015
	 */
	int countByExample(TimeSheetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table time_sheet
	 * 
	 * @mbggenerated Mon Oct 12 13:12:27 IST 2015
	 */
	int deleteByExample(TimeSheetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table time_sheet
	 * 
	 * @mbggenerated Mon Oct 12 13:12:27 IST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table time_sheet
	 * 
	 * @mbggenerated Mon Oct 12 13:12:27 IST 2015
	 */
	int insert(TimeSheet record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table time_sheet
	 * 
	 * @mbggenerated Mon Oct 12 13:12:27 IST 2015
	 */
	int insertSelective(TimeSheet record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table time_sheet
	 * 
	 * @mbggenerated Mon Oct 12 13:12:27 IST 2015
	 */
	List<TimeSheet> selectByExample(TimeSheetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table time_sheet
	 * 
	 * @mbggenerated Mon Oct 12 13:12:27 IST 2015
	 */
	TimeSheet selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table time_sheet
	 * 
	 * @mbggenerated Mon Oct 12 13:12:27 IST 2015
	 */
	int updateByExampleSelective(@Param("record") TimeSheet record, @Param("example") TimeSheetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table time_sheet
	 * 
	 * @mbggenerated Mon Oct 12 13:12:27 IST 2015
	 */
	int updateByExample(@Param("record") TimeSheet record, @Param("example") TimeSheetExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table time_sheet
	 * 
	 * @mbggenerated Mon Oct 12 13:12:27 IST 2015
	 */
	int updateByPrimaryKeySelective(TimeSheet record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table time_sheet
	 * 
	 * @mbggenerated Mon Oct 12 13:12:27 IST 2015
	 */
	int updateByPrimaryKey(TimeSheet record);
}