package com.newput.domain;

import java.io.Serializable;

public class DateSheet implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column date_sheet.id
	 * @mbggenerated  Wed Oct 07 14:48:54 IST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column date_sheet.emp_id
	 * @mbggenerated  Wed Oct 07 14:48:54 IST 2015
	 */
	private Integer empId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column date_sheet.work_date
	 * @mbggenerated  Wed Oct 07 14:48:54 IST 2015
	 */
	private Long workDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column date_sheet.work_desc
	 * @mbggenerated  Wed Oct 07 14:48:54 IST 2015
	 */
	private String workDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column date_sheet.created
	 * @mbggenerated  Wed Oct 07 14:48:54 IST 2015
	 */
	private Long created;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column date_sheet.updated
	 * @mbggenerated  Wed Oct 07 14:48:54 IST 2015
	 */
	private Long updated;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table date_sheet
	 * @mbggenerated  Wed Oct 07 14:48:54 IST 2015
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column date_sheet.id
	 * @return  the value of date_sheet.id
	 * @mbggenerated  Wed Oct 07 14:48:54 IST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column date_sheet.id
	 * @param id  the value for date_sheet.id
	 * @mbggenerated  Wed Oct 07 14:48:54 IST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column date_sheet.emp_id
	 * @return  the value of date_sheet.emp_id
	 * @mbggenerated  Wed Oct 07 14:48:54 IST 2015
	 */
	public Integer getEmpId() {
		return empId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column date_sheet.emp_id
	 * @param empId  the value for date_sheet.emp_id
	 * @mbggenerated  Wed Oct 07 14:48:54 IST 2015
	 */
	public void setEmpId(Integer empId) {
		this.empId = empId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column date_sheet.work_date
	 * @return  the value of date_sheet.work_date
	 * @mbggenerated  Wed Oct 07 14:48:54 IST 2015
	 */
	public Long getWorkDate() {
		return workDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column date_sheet.work_date
	 * @param workDate  the value for date_sheet.work_date
	 * @mbggenerated  Wed Oct 07 14:48:54 IST 2015
	 */
	public void setWorkDate(Long workDate) {
		this.workDate = workDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column date_sheet.work_desc
	 * @return  the value of date_sheet.work_desc
	 * @mbggenerated  Wed Oct 07 14:48:54 IST 2015
	 */
	public String getWorkDesc() {
		return workDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column date_sheet.work_desc
	 * @param workDesc  the value for date_sheet.work_desc
	 * @mbggenerated  Wed Oct 07 14:48:54 IST 2015
	 */
	public void setWorkDesc(String workDesc) {
		this.workDesc = workDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column date_sheet.created
	 * @return  the value of date_sheet.created
	 * @mbggenerated  Wed Oct 07 14:48:54 IST 2015
	 */
	public Long getCreated() {
		return created;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column date_sheet.created
	 * @param created  the value for date_sheet.created
	 * @mbggenerated  Wed Oct 07 14:48:54 IST 2015
	 */
	public void setCreated(Long created) {
		this.created = created;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column date_sheet.updated
	 * @return  the value of date_sheet.updated
	 * @mbggenerated  Wed Oct 07 14:48:54 IST 2015
	 */
	public Long getUpdated() {
		return updated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column date_sheet.updated
	 * @param updated  the value for date_sheet.updated
	 * @mbggenerated  Wed Oct 07 14:48:54 IST 2015
	 */
	public void setUpdated(Long updated) {
		this.updated = updated;
	}
}