package com.newput.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import org.springframework.stereotype.Service;

@Service
public class Employee implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.id
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.first_name
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	private String firstName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.last_name
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	private String lastName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.email
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.dob
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	private Date dob;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.doj
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	private Date doj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.address
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.contact
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	private String contact;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.gender
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	private String gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.password
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.status
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	private Boolean status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.password_verification
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	private Boolean passwordVerification;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.role
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	private String role;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.created
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	private Long created;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.updated
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	private Long updated;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.time_zone
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	private BigDecimal timeZone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.v_token
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	private String vToken;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.p_token
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	private String pToken;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.p_expire_at
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	private Long pExpireAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table employee
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.id
	 * @return  the value of employee.id
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.id
	 * @param id  the value for employee.id
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.first_name
	 * @return  the value of employee.first_name
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public String getFirstName() {
		return firstName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.first_name
	 * @param firstName  the value for employee.first_name
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.last_name
	 * @return  the value of employee.last_name
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public String getLastName() {
		return lastName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.last_name
	 * @param lastName  the value for employee.last_name
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.email
	 * @return  the value of employee.email
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.email
	 * @param email  the value for employee.email
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.dob
	 * @return  the value of employee.dob
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public Date getDob() {
		return dob;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.dob
	 * @param dob  the value for employee.dob
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public void setDob(Date dob) {
		this.dob = dob;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.doj
	 * @return  the value of employee.doj
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public Date getDoj() {
		return doj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.doj
	 * @param doj  the value for employee.doj
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public void setDoj(Date doj) {
		this.doj = doj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.address
	 * @return  the value of employee.address
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.address
	 * @param address  the value for employee.address
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.contact
	 * @return  the value of employee.contact
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public String getContact() {
		return contact;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.contact
	 * @param contact  the value for employee.contact
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public void setContact(String contact) {
		this.contact = contact;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.gender
	 * @return  the value of employee.gender
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public String getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.gender
	 * @param gender  the value for employee.gender
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public void setGender(String gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.password
	 * @return  the value of employee.password
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.password
	 * @param password  the value for employee.password
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.status
	 * @return  the value of employee.status
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public Boolean getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.status
	 * @param status  the value for employee.status
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public void setStatus(Boolean status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.password_verification
	 * @return  the value of employee.password_verification
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public Boolean getPasswordVerification() {
		return passwordVerification;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.password_verification
	 * @param passwordVerification  the value for employee.password_verification
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public void setPasswordVerification(Boolean passwordVerification) {
		this.passwordVerification = passwordVerification;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.role
	 * @return  the value of employee.role
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public String getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.role
	 * @param role  the value for employee.role
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public void setRole(String role) {
		this.role = role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.created
	 * @return  the value of employee.created
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public Long getCreated() {
		return created;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.created
	 * @param created  the value for employee.created
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public void setCreated(Long created) {
		this.created = created;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.updated
	 * @return  the value of employee.updated
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public Long getUpdated() {
		return updated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.updated
	 * @param updated  the value for employee.updated
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public void setUpdated(Long updated) {
		this.updated = updated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.time_zone
	 * @return  the value of employee.time_zone
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public BigDecimal getTimeZone() {
		return timeZone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.time_zone
	 * @param timeZone  the value for employee.time_zone
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public void setTimeZone(BigDecimal timeZone) {
		this.timeZone = timeZone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.v_token
	 * @return  the value of employee.v_token
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public String getvToken() {
		return vToken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.v_token
	 * @param vToken  the value for employee.v_token
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public void setvToken(String vToken) {
		this.vToken = vToken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.p_token
	 * @return  the value of employee.p_token
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public String getpToken() {
		return pToken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.p_token
	 * @param pToken  the value for employee.p_token
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public void setpToken(String pToken) {
		this.pToken = pToken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.p_expire_at
	 * @return  the value of employee.p_expire_at
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public Long getpExpireAt() {
		return pExpireAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.p_expire_at
	 * @param pExpireAt  the value for employee.p_expire_at
	 * @mbggenerated  Thu Oct 08 11:59:16 IST 2015
	 */
	public void setpExpireAt(Long pExpireAt) {
		this.pExpireAt = pExpireAt;
	}
}